server:
  port: 9090
  tomcat:
    threads:
      max: 50  # 允许的最大线程数
    accept-count: 50  # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://10.211.55.8:3306/cloud_product?characterEncoding=utf8&useSSL=false
    username: root
    password: xzl.995
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 10.211.55.7:8848
    openfeign:
      okhttp:
        enabled: true # 开启OKHttp功能，Feign的底层实现不支持连接池，因此开启支持连接池的okhttp
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true  # 开启请求方式前缀
feign:
  sentinel:
    enabled: true  # 开启feign对sentinel的支持

# 设置 Mybatis 的 xml 保存路径
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
