server:
  port: 9090
  tomcat:
    threads:
      max: 50  # 允许的最大线程数
    accept-count: 50  # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
spring:
  application:
    name: product-service
zl:
  db:
    host: 10.211.55.8
    database: cloud_product
