server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://10.211.55.8:3306/cloud_product?characterEncoding=utf8&useSSL=false
    username: root
    password: xzl.995
    driver-class-name: com.mysql.cj.jdbc.Driver
# 设置 Mybatis 的 xml 保存路径
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
    map-underscore-to-camel-case: true

