server:
  port: 9090
  tomcat:
    threads:
      max: 50  # 允许的最大线程数
    accept-count: 50  # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
spring:
  application:
    name: product-service
  rabbitmq:
    host: 10.211.55.7
    port: 5672
    username: zl-mq
    password: xzl.995
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制

zl:
  db:
    host: 10.211.55.8
    database: cloud_product
